---
version: "2"
linters:
  enable:
    - govet
    - gocyclo
  exclusions:
    rules:
      - source: "^\\s*defer\\s+"
        linters: ["errcheck"]
formatters:
  enable:
    - gofmt
    - goimports
